// Generated by CoffeeScript 1.6.3
var closeAlerts, equidist, formValidation, isMobile, openAlert, popupWindow, validarEmail, _in, _out;

_in = function(element) {
  return element.addClass("in");
};

_out = function(element) {
  element.addClass("out");
  return setTimeout(function() {
    return element.removeClass("in out");
  }, 500);
};

popupWindow = function(url, w, h) {
  var left, top;
  left = ($(window).width() / 2) - (w / 2);
  top = ($(window).height() / 2) - (h / 2);
  return window.open(url, "Compartir", 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);
};

validarEmail = function(elemento, valor) {
  if (/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(valor)) {
    return true;
  } else {
    return false;
  }
};

equidist = function() {
  return $(".equidist").each(function() {
    var _left, _this, _top;
    _this = $(this);
    _left = (_this.parent().width() - _this.width()) / 2;
    if (_left < 0) {
      _left = 0;
    }
    _top = (_this.parent().height() - _this.height()) / 2;
    if (_top < 0) {
      _top = 0;
    }
    return _this.css({
      left: _left + "px",
      top: _top + "px"
    });
  });
};

openAlert = function(options) {
  var buttons, close, content, html, title;
  title = "";
  content = "";
  buttons = "";
  close = "";
  if (options.title) {
    title = "<h2>" + options.title + "</h2>";
  }
  if (options.content) {
    content = "<div class='alert-content'>" + options.content + "</p>";
  }
  if (options.close === void 0) {
    options.close = true;
  }
  if (options.close === true) {
    close = '<button class="close false">X</button>';
  }
  if (options.buttons) {
    buttons += options.buttons + " ";
  }
  if (options.cancelar === true) {
    buttons += '<button class="button false">Cancelar</button> ';
  }
  if (options.aceptar === true) {
    buttons += '<button class="button true">Aceptar</button> ';
  }
  html = '<div class="alert in ' + options.cssclass + '">' + '<div class="alert-light false"></div>' + '<div class="alert-box equidist">' + '<div class="inner">' + close + title + content + '<div class="buttons">' + buttons + '</div>' + '</div>' + '</div>' + '</div>';
  $("body").append(html);
  equidist();
  return $(".alert .true, .alert .false").unbind("click").bind("click", function() {
    var alertorigin;
    if ($(this).parent().is(".alert")) {
      alertorigin = $(this).parent();
    }
    if ($(this).parent().parent().is(".alert")) {
      alertorigin = $(this).parent().parent();
    }
    if ($(this).parent().parent().parent().is(".alert")) {
      alertorigin = $(this).parent().parent().parent();
    }
    if ($(this).parent().parent().parent().parent().is(".alert")) {
      alertorigin = $(this).parent().parent().parent().parent();
    }
    if ($(this).parent().parent().parent().parent().parent().is(".alert")) {
      alertorigin = $(this).parent().parent().parent().parent().parent();
    }
    alertorigin.addClass("out");
    setTimeout(function() {
      return alertorigin.remove();
    }, 200);
    if ($(this).hasClass("true") && options.callback_true) {
      options.callback_true();
    }
    if ($(this).hasClass("false") && options.callback_false) {
      options.callback_false();
    }
    return true;
  });
};

closeAlerts = function() {
  $(".alert").addClass("out");
  return setTimeout(function() {
    return $(".alert").remove();
  }, 200);
};

isMobile = function() {
  if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
    return true;
  } else {
    return false;
  }
};

formValidation = function(forms, callback) {
  if (callback == null) {
    callback = false;
  }
  return forms.each(function() {
    var form;
    form = $(this);
    form.find("input,textarea,select").each(function() {
      var _this;
      _this = $(this);
      _this.addClass($(this).attr("type"));
      _this.after("<span class='icon-error icon-" + $(this).attr("type") + "'><span></span>x</span>");
      return _this.live("blur", function() {
        if (!$(this).hasClass("optional") && $(this).attr("type") !== "submit" && $(this).attr("type") !== "hidden") {
          if (!_this.val()) {
            _this.addClass("error");
            _this.parent().addClass("error");
          } else {
            _this.removeClass("error");
            _this.parent().removeClass("error");
          }
          if (_this.hasClass("email")) {
            if (validarEmail(_this, _this.val())) {
              _this.removeClass("error");
              return _this.parent().removeClass("error");
            } else {
              _this.addClass("error");
              return _this.parent().addClass("error");
            }
          }
        }
      });
    });
    if (form.find(".rut").length) {
      form.find("input.rut").each(function() {
        var _this;
        _this = $(this);
        return _this.Rut({
          format_on: 'keyup',
          on_success: function() {
            _this.removeClass("error");
            return _this.parent().removeClass("error");
          },
          on_error: function() {
            _this.addClass("error");
            return _this.parent().addClass("error");
          }
        });
      });
    }
    form.find("input.number").each(function() {
      return $(this).removeClass("number").wrap("<div class='number'>").after("<button class='mas'>+</button><button class='menos'>-</button>");
    });
    form.find(".number button").live("click", function() {
      var _input, _max, _min, _steps, _val;
      _input = $(this).parent().find("input");
      _max = parseInt(_input.attr("data-max"));
      _min = parseInt(_input.attr("data-min"));
      _steps = parseInt(_input.attr("data-steps"));
      if (!_steps) {
        _steps = 1;
      }
      _val = parseInt(_input.val());
      if ($(this).hasClass("mas")) {
        _val = _val + _steps;
      }
      if ($(this).hasClass("menos")) {
        _val = _val - _steps;
      }
      if (_val >= _max) {
        _val = _max;
      }
      if (_val <= _min) {
        _val = _min;
      }
      _input.val(_val);
      return false;
    });
    form.find(".number input").live("blur", function() {
      var _input, _max, _min, _val;
      _input = $(this);
      _max = parseInt(_input.attr("data-max"));
      _min = parseInt(_input.attr("data-min"));
      _val = parseInt(_input.val());
      if (_val >= _max) {
        _val = _max;
      }
      if (_val <= _min) {
        _val = _min;
      }
      _input.val(_val);
      return true;
    });
    return form.submit(function() {
      var enviar, _this;
      enviar = true;
      _this = $(this);
      _this.find("input, textarea, select").each(function() {
        if (!$(this).hasClass("optional") && $(this).attr("type") !== "submit" && $(this).attr("type") !== "hidden") {
          if ($(this).attr("type") === "checkbox" || $(this).attr("type") === "radio") {
            if (!$(this).find("input[name='" + $(this).attr("name") + "']:checked").length) {
              enviar = false;
              $(this).addClass("error");
              $(this).parent().addClass("error");
            } else {
              $(this).removeClass("error");
              $(this).parent().removeClass("error");
            }
          } else {
            if (!$(this).val()) {
              enviar = false;
              $(this).addClass("error");
              $(this).parent().addClass("error");
            } else {
              $(this).removeClass("error");
              $(this).parent().removeClass("error");
            }
          }
          if ($(this).hasClass("email")) {
            if (validarEmail($(this), $(this).val())) {
              $(this).removeClass("error");
              return $(this).parent().removeClass("error");
            } else {
              enviar = false;
              $(this).addClass("error");
              return $(this).parent().addClass("error");
            }
          }
        }
      });
      if (enviar === true) {
        if (callback) {
          callback();
          enviar = false;
        }
      }
      return enviar;
    });
  });
};

/* --------------------------------------------
     Begin scripts.coffee
--------------------------------------------
*/


$(document).ready(function() {
  var resizing_timeout;
  resizing_timeout = false;
  $(window).resize(function() {
    var resizing;
    equidist();
    resizing = true;
    clearTimeout(resizing_timeout);
    return resizing_timeout = setTimeout(function() {
      $container.isotope({
        relayout: true
      });
      return resizing = false;
    }, 200);
  });
  $("[data-tooltip]").each(function() {
    return $(this).append("<span class='newtooltip'><span class='newtooltip-container'><span class='newtooltip-triangle'></span><span class='newtooltip-content'>" + $(this).attr("data-tooltip") + "</span></span></span>");
  });
  $(".box-tabs .box-tabs-header a").live("click", function() {
    var index, parent;
    index = $(this).index();
    parent = $(this).parent().parent();
    parent.find(".box-tabs-header a").removeClass("active");
    parent.find(".box-tabs-header a").eq(index).addClass("active");
    parent.find(".box-tabs-content").removeClass("active");
    parent.find(".box-tabs-content").eq(index).addClass("active");
    $container.isotope({
      relayout: true
    });
    return false;
  });
  $(".goto").click(function() {
    return $("html,body").animate({
      scrollTop: $(".gotoend").offset().top - $("header").height() - 20
    });
  });
  $(".load-more").click(function() {
    $(this).html("CARGANDO...");
    $.ajax({
      type: "GET",
      url: $(this).attr("href"),
      async: false,
      success: function(html) {
        var $newItems, link_next;
        html = $(html);
        $newItems = html.find(".articles >");
        link_next = html.find(".load-more").attr("href");
        $container.isotope('insert', $newItems);
        setTimeout(function() {
          $(".load-more").html("CARGAR MÁS CONTENIDO").attr("href", link_next);
          $container.isotope({
            relayout: true
          });
          return equidist();
        }, 500);
        return $(window).load(function() {
          $container.isotope({
            relayout: true
          });
          return equidist();
        });
      }
    });
    return false;
  });
  formValidation($("form.controls"));
  return setTimeout(function() {
    var _n_slides;
    if ($("#sliderhome").length) {
      _n_slides = 0;
      $("#sliderhome .royalSlider .rsContent").each(function() {
        $(this).attr("data-slide", $(this).index());
        return _n_slides++;
      });
      return $("#sliderhome .royalSlider").royalSlider({
        imageScaleMode: 'fit',
        sliderDrag: false,
        arrowsNavAutoHide: false,
        loop: true,
        slidesSpacing: 10,
        transitionSpeed: 600,
        autoPlay: {
          enabled: true,
          pauseOnHover: true,
          delay: 4000
        },
        imageScalePadding: 0,
        addActiveClass: true,
        navigateByClick: false,
        autoHeight: true
      });
    }
  }, 50);
});
